package com.unionpay.dao.repository;

import java.util.List;

import com.unionpay.dao.model.InterfaceKey;

public interface InterfaceKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    int insert(InterfaceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    int insertSelective(InterfaceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    InterfaceKey selectByPrimaryKey(String keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InterfaceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(InterfaceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InterfaceKey record);
    
	/**
     * 查询接口密钥列表
     * 
     * @param interfaceKey 接口密钥信息
     * @return 接口密钥集合
     */
	public List<InterfaceKey> selectInterfaceKeyList(InterfaceKey interfaceKey);
}