package com.unionpay.dao.repository;

import com.unionpay.dao.model.UpAccountTran;

/**
 * 
 * <p>Title: UpAccountTranMapper</p>
 * <p>Description:积分账户变动流水-数据层</p>
 * <p>Company: eh</p>
 * @author li liang zhong
 * @date 2019年3月21日 下午1:53:28
 * @version 1.0
 *
 */
public interface UpAccountTranMapper 
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tranId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    int insert(UpAccountTran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    int insertSelective(UpAccountTran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    UpAccountTran selectByPrimaryKey(String tranId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UpAccountTran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UpAccountTran record);
}