package com.unionpay.dao.model;

import java.io.Serializable;

public class InterfaceKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_interface_key.key_id
     *
     * @mbg.generated
     */
    private String keyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_interface_key.branch_id
     *
     * @mbg.generated
     */
    private String branchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_interface_key.interface_id
     *
     * @mbg.generated
     */
    private String interfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_interface_key.key_type
     *
     * @mbg.generated
     */
    private String keyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_interface_key.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_interface_key.key_content
     *
     * @mbg.generated
     */
    private String keyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_interface_key.key_id
     *
     * @return the value of up_interface_key.key_id
     *
     * @mbg.generated
     */
    public String getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_interface_key.key_id
     *
     * @param keyId the value for up_interface_key.key_id
     *
     * @mbg.generated
     */
    public void setKeyId(String keyId) {
        this.keyId = keyId == null ? null : keyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_interface_key.branch_id
     *
     * @return the value of up_interface_key.branch_id
     *
     * @mbg.generated
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_interface_key.branch_id
     *
     * @param branchId the value for up_interface_key.branch_id
     *
     * @mbg.generated
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_interface_key.interface_id
     *
     * @return the value of up_interface_key.interface_id
     *
     * @mbg.generated
     */
    public String getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_interface_key.interface_id
     *
     * @param interfaceId the value for up_interface_key.interface_id
     *
     * @mbg.generated
     */
    public void setInterfaceId(String interfaceId) {
        this.interfaceId = interfaceId == null ? null : interfaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_interface_key.key_type
     *
     * @return the value of up_interface_key.key_type
     *
     * @mbg.generated
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_interface_key.key_type
     *
     * @param keyType the value for up_interface_key.key_type
     *
     * @mbg.generated
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType == null ? null : keyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_interface_key.status
     *
     * @return the value of up_interface_key.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_interface_key.status
     *
     * @param status the value for up_interface_key.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_interface_key.key_content
     *
     * @return the value of up_interface_key.key_content
     *
     * @mbg.generated
     */
    public String getKeyContent() {
        return keyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_interface_key.key_content
     *
     * @param keyContent the value for up_interface_key.key_content
     *
     * @mbg.generated
     */
    public void setKeyContent(String keyContent) {
        this.keyContent = keyContent == null ? null : keyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InterfaceKey other = (InterfaceKey) that;
        return (this.getKeyId() == null ? other.getKeyId() == null : this.getKeyId().equals(other.getKeyId()))
            && (this.getBranchId() == null ? other.getBranchId() == null : this.getBranchId().equals(other.getBranchId()))
            && (this.getInterfaceId() == null ? other.getInterfaceId() == null : this.getInterfaceId().equals(other.getInterfaceId()))
            && (this.getKeyType() == null ? other.getKeyType() == null : this.getKeyType().equals(other.getKeyType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getKeyContent() == null ? other.getKeyContent() == null : this.getKeyContent().equals(other.getKeyContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getKeyId() == null) ? 0 : getKeyId().hashCode());
        result = prime * result + ((getBranchId() == null) ? 0 : getBranchId().hashCode());
        result = prime * result + ((getInterfaceId() == null) ? 0 : getInterfaceId().hashCode());
        result = prime * result + ((getKeyType() == null) ? 0 : getKeyType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getKeyContent() == null) ? 0 : getKeyContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_interface_key
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", keyId=").append(keyId);
        sb.append(", branchId=").append(branchId);
        sb.append(", interfaceId=").append(interfaceId);
        sb.append(", keyType=").append(keyType);
        sb.append(", status=").append(status);
        sb.append(", keyContent=").append(keyContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}