package com.unionpay.dao.model;

import java.io.Serializable;
import java.util.Date;

public class MchntResult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.result_id
     *
     * @mbg.generated
     */
    private Integer resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.batch_no
     *
     * @mbg.generated
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.mchnt_no
     *
     * @mbg.generated
     */
    private String mchntNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.scorecard_id
     *
     * @mbg.generated
     */
    private Integer scorecardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.total_score
     *
     * @mbg.generated
     */
    private Integer totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.mchnt_grade
     *
     * @mbg.generated
     */
    private Integer mchntGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.grade_time
     *
     * @mbg.generated
     */
    private Date gradeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.grade_type
     *
     * @mbg.generated
     */
    private String gradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.policy_id
     *
     * @mbg.generated
     */
    private String policyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.grade_org_id
     *
     * @mbg.generated
     */
    private String gradeOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_mchnt_result.oper_no
     *
     * @mbg.generated
     */
    private String operNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_mchnt_result
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.result_id
     *
     * @return the value of g_mchnt_result.result_id
     *
     * @mbg.generated
     */
    public Integer getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.result_id
     *
     * @param resultId the value for g_mchnt_result.result_id
     *
     * @mbg.generated
     */
    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.batch_no
     *
     * @return the value of g_mchnt_result.batch_no
     *
     * @mbg.generated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.batch_no
     *
     * @param batchNo the value for g_mchnt_result.batch_no
     *
     * @mbg.generated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.mchnt_no
     *
     * @return the value of g_mchnt_result.mchnt_no
     *
     * @mbg.generated
     */
    public String getMchntNo() {
        return mchntNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.mchnt_no
     *
     * @param mchntNo the value for g_mchnt_result.mchnt_no
     *
     * @mbg.generated
     */
    public void setMchntNo(String mchntNo) {
        this.mchntNo = mchntNo == null ? null : mchntNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.scorecard_id
     *
     * @return the value of g_mchnt_result.scorecard_id
     *
     * @mbg.generated
     */
    public Integer getScorecardId() {
        return scorecardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.scorecard_id
     *
     * @param scorecardId the value for g_mchnt_result.scorecard_id
     *
     * @mbg.generated
     */
    public void setScorecardId(Integer scorecardId) {
        this.scorecardId = scorecardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.total_score
     *
     * @return the value of g_mchnt_result.total_score
     *
     * @mbg.generated
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.total_score
     *
     * @param totalScore the value for g_mchnt_result.total_score
     *
     * @mbg.generated
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.mchnt_grade
     *
     * @return the value of g_mchnt_result.mchnt_grade
     *
     * @mbg.generated
     */
    public Integer getMchntGrade() {
        return mchntGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.mchnt_grade
     *
     * @param mchntGrade the value for g_mchnt_result.mchnt_grade
     *
     * @mbg.generated
     */
    public void setMchntGrade(Integer mchntGrade) {
        this.mchntGrade = mchntGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.grade_time
     *
     * @return the value of g_mchnt_result.grade_time
     *
     * @mbg.generated
     */
    public Date getGradeTime() {
        return gradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.grade_time
     *
     * @param gradeTime the value for g_mchnt_result.grade_time
     *
     * @mbg.generated
     */
    public void setGradeTime(Date gradeTime) {
        this.gradeTime = gradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.grade_type
     *
     * @return the value of g_mchnt_result.grade_type
     *
     * @mbg.generated
     */
    public String getGradeType() {
        return gradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.grade_type
     *
     * @param gradeType the value for g_mchnt_result.grade_type
     *
     * @mbg.generated
     */
    public void setGradeType(String gradeType) {
        this.gradeType = gradeType == null ? null : gradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.policy_id
     *
     * @return the value of g_mchnt_result.policy_id
     *
     * @mbg.generated
     */
    public String getPolicyId() {
        return policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.policy_id
     *
     * @param policyId the value for g_mchnt_result.policy_id
     *
     * @mbg.generated
     */
    public void setPolicyId(String policyId) {
        this.policyId = policyId == null ? null : policyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.grade_org_id
     *
     * @return the value of g_mchnt_result.grade_org_id
     *
     * @mbg.generated
     */
    public String getGradeOrgId() {
        return gradeOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.grade_org_id
     *
     * @param gradeOrgId the value for g_mchnt_result.grade_org_id
     *
     * @mbg.generated
     */
    public void setGradeOrgId(String gradeOrgId) {
        this.gradeOrgId = gradeOrgId == null ? null : gradeOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.update_time
     *
     * @return the value of g_mchnt_result.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.update_time
     *
     * @param updateTime the value for g_mchnt_result.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_mchnt_result.oper_no
     *
     * @return the value of g_mchnt_result.oper_no
     *
     * @mbg.generated
     */
    public String getOperNo() {
        return operNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_mchnt_result.oper_no
     *
     * @param operNo the value for g_mchnt_result.oper_no
     *
     * @mbg.generated
     */
    public void setOperNo(String operNo) {
        this.operNo = operNo == null ? null : operNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_mchnt_result
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MchntResult other = (MchntResult) that;
        return (this.getResultId() == null ? other.getResultId() == null : this.getResultId().equals(other.getResultId()))
            && (this.getBatchNo() == null ? other.getBatchNo() == null : this.getBatchNo().equals(other.getBatchNo()))
            && (this.getMchntNo() == null ? other.getMchntNo() == null : this.getMchntNo().equals(other.getMchntNo()))
            && (this.getScorecardId() == null ? other.getScorecardId() == null : this.getScorecardId().equals(other.getScorecardId()))
            && (this.getTotalScore() == null ? other.getTotalScore() == null : this.getTotalScore().equals(other.getTotalScore()))
            && (this.getMchntGrade() == null ? other.getMchntGrade() == null : this.getMchntGrade().equals(other.getMchntGrade()))
            && (this.getGradeTime() == null ? other.getGradeTime() == null : this.getGradeTime().equals(other.getGradeTime()))
            && (this.getGradeType() == null ? other.getGradeType() == null : this.getGradeType().equals(other.getGradeType()))
            && (this.getPolicyId() == null ? other.getPolicyId() == null : this.getPolicyId().equals(other.getPolicyId()))
            && (this.getGradeOrgId() == null ? other.getGradeOrgId() == null : this.getGradeOrgId().equals(other.getGradeOrgId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getOperNo() == null ? other.getOperNo() == null : this.getOperNo().equals(other.getOperNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_mchnt_result
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getResultId() == null) ? 0 : getResultId().hashCode());
        result = prime * result + ((getBatchNo() == null) ? 0 : getBatchNo().hashCode());
        result = prime * result + ((getMchntNo() == null) ? 0 : getMchntNo().hashCode());
        result = prime * result + ((getScorecardId() == null) ? 0 : getScorecardId().hashCode());
        result = prime * result + ((getTotalScore() == null) ? 0 : getTotalScore().hashCode());
        result = prime * result + ((getMchntGrade() == null) ? 0 : getMchntGrade().hashCode());
        result = prime * result + ((getGradeTime() == null) ? 0 : getGradeTime().hashCode());
        result = prime * result + ((getGradeType() == null) ? 0 : getGradeType().hashCode());
        result = prime * result + ((getPolicyId() == null) ? 0 : getPolicyId().hashCode());
        result = prime * result + ((getGradeOrgId() == null) ? 0 : getGradeOrgId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getOperNo() == null) ? 0 : getOperNo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_mchnt_result
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resultId=").append(resultId);
        sb.append(", batchNo=").append(batchNo);
        sb.append(", mchntNo=").append(mchntNo);
        sb.append(", scorecardId=").append(scorecardId);
        sb.append(", totalScore=").append(totalScore);
        sb.append(", mchntGrade=").append(mchntGrade);
        sb.append(", gradeTime=").append(gradeTime);
        sb.append(", gradeType=").append(gradeType);
        sb.append(", policyId=").append(policyId);
        sb.append(", gradeOrgId=").append(gradeOrgId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", operNo=").append(operNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}