package com.unionpay.dao.model;

import java.io.Serializable;
import java.util.Date;

public class UpAccountTran implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.tran_id
     *
     * @mbg.generated
     */
    private String tranId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.tran_type
     *
     * @mbg.generated
     */
    private String tranType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.tran_time
     *
     * @mbg.generated
     */
    private Date tranTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.point_amount
     *
     * @mbg.generated
     */
    private Long pointAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.merch_id
     *
     * @mbg.generated
     */
    private String merchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.initial_balance
     *
     * @mbg.generated
     */
    private Long initialBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.end_balance
     *
     * @mbg.generated
     */
    private Long endBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.integral_account_no
     *
     * @mbg.generated
     */
    private String integralAccountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.org_code
     *
     * @mbg.generated
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.tran_remark
     *
     * @mbg.generated
     */
    private String tranRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column up_account_tran.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.tran_id
     *
     * @return the value of up_account_tran.tran_id
     *
     * @mbg.generated
     */
    public String getTranId() {
        return tranId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.tran_id
     *
     * @param tranId the value for up_account_tran.tran_id
     *
     * @mbg.generated
     */
    public void setTranId(String tranId) {
        this.tranId = tranId == null ? null : tranId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.tran_type
     *
     * @return the value of up_account_tran.tran_type
     *
     * @mbg.generated
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.tran_type
     *
     * @param tranType the value for up_account_tran.tran_type
     *
     * @mbg.generated
     */
    public void setTranType(String tranType) {
        this.tranType = tranType == null ? null : tranType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.tran_time
     *
     * @return the value of up_account_tran.tran_time
     *
     * @mbg.generated
     */
    public Date getTranTime() {
        return tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.tran_time
     *
     * @param tranTime the value for up_account_tran.tran_time
     *
     * @mbg.generated
     */
    public void setTranTime(Date tranTime) {
        this.tranTime = tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.point_amount
     *
     * @return the value of up_account_tran.point_amount
     *
     * @mbg.generated
     */
    public Long getPointAmount() {
        return pointAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.point_amount
     *
     * @param pointAmount the value for up_account_tran.point_amount
     *
     * @mbg.generated
     */
    public void setPointAmount(Long pointAmount) {
        this.pointAmount = pointAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.merch_id
     *
     * @return the value of up_account_tran.merch_id
     *
     * @mbg.generated
     */
    public String getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.merch_id
     *
     * @param merchId the value for up_account_tran.merch_id
     *
     * @mbg.generated
     */
    public void setMerchId(String merchId) {
        this.merchId = merchId == null ? null : merchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.initial_balance
     *
     * @return the value of up_account_tran.initial_balance
     *
     * @mbg.generated
     */
    public Long getInitialBalance() {
        return initialBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.initial_balance
     *
     * @param initialBalance the value for up_account_tran.initial_balance
     *
     * @mbg.generated
     */
    public void setInitialBalance(Long initialBalance) {
        this.initialBalance = initialBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.end_balance
     *
     * @return the value of up_account_tran.end_balance
     *
     * @mbg.generated
     */
    public Long getEndBalance() {
        return endBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.end_balance
     *
     * @param endBalance the value for up_account_tran.end_balance
     *
     * @mbg.generated
     */
    public void setEndBalance(Long endBalance) {
        this.endBalance = endBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.integral_account_no
     *
     * @return the value of up_account_tran.integral_account_no
     *
     * @mbg.generated
     */
    public String getIntegralAccountNo() {
        return integralAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.integral_account_no
     *
     * @param integralAccountNo the value for up_account_tran.integral_account_no
     *
     * @mbg.generated
     */
    public void setIntegralAccountNo(String integralAccountNo) {
        this.integralAccountNo = integralAccountNo == null ? null : integralAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.status
     *
     * @return the value of up_account_tran.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.status
     *
     * @param status the value for up_account_tran.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.org_code
     *
     * @return the value of up_account_tran.org_code
     *
     * @mbg.generated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.org_code
     *
     * @param orgCode the value for up_account_tran.org_code
     *
     * @mbg.generated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.tran_remark
     *
     * @return the value of up_account_tran.tran_remark
     *
     * @mbg.generated
     */
    public String getTranRemark() {
        return tranRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.tran_remark
     *
     * @param tranRemark the value for up_account_tran.tran_remark
     *
     * @mbg.generated
     */
    public void setTranRemark(String tranRemark) {
        this.tranRemark = tranRemark == null ? null : tranRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.remark
     *
     * @return the value of up_account_tran.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.remark
     *
     * @param remark the value for up_account_tran.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column up_account_tran.created_time
     *
     * @return the value of up_account_tran.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column up_account_tran.created_time
     *
     * @param createdTime the value for up_account_tran.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UpAccountTran other = (UpAccountTran) that;
        return (this.getTranId() == null ? other.getTranId() == null : this.getTranId().equals(other.getTranId()))
            && (this.getTranType() == null ? other.getTranType() == null : this.getTranType().equals(other.getTranType()))
            && (this.getTranTime() == null ? other.getTranTime() == null : this.getTranTime().equals(other.getTranTime()))
            && (this.getPointAmount() == null ? other.getPointAmount() == null : this.getPointAmount().equals(other.getPointAmount()))
            && (this.getMerchId() == null ? other.getMerchId() == null : this.getMerchId().equals(other.getMerchId()))
            && (this.getInitialBalance() == null ? other.getInitialBalance() == null : this.getInitialBalance().equals(other.getInitialBalance()))
            && (this.getEndBalance() == null ? other.getEndBalance() == null : this.getEndBalance().equals(other.getEndBalance()))
            && (this.getIntegralAccountNo() == null ? other.getIntegralAccountNo() == null : this.getIntegralAccountNo().equals(other.getIntegralAccountNo()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getTranRemark() == null ? other.getTranRemark() == null : this.getTranRemark().equals(other.getTranRemark()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTranId() == null) ? 0 : getTranId().hashCode());
        result = prime * result + ((getTranType() == null) ? 0 : getTranType().hashCode());
        result = prime * result + ((getTranTime() == null) ? 0 : getTranTime().hashCode());
        result = prime * result + ((getPointAmount() == null) ? 0 : getPointAmount().hashCode());
        result = prime * result + ((getMerchId() == null) ? 0 : getMerchId().hashCode());
        result = prime * result + ((getInitialBalance() == null) ? 0 : getInitialBalance().hashCode());
        result = prime * result + ((getEndBalance() == null) ? 0 : getEndBalance().hashCode());
        result = prime * result + ((getIntegralAccountNo() == null) ? 0 : getIntegralAccountNo().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getTranRemark() == null) ? 0 : getTranRemark().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table up_account_tran
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tranId=").append(tranId);
        sb.append(", tranType=").append(tranType);
        sb.append(", tranTime=").append(tranTime);
        sb.append(", pointAmount=").append(pointAmount);
        sb.append(", merchId=").append(merchId);
        sb.append(", initialBalance=").append(initialBalance);
        sb.append(", endBalance=").append(endBalance);
        sb.append(", integralAccountNo=").append(integralAccountNo);
        sb.append(", status=").append(status);
        sb.append(", orgCode=").append(orgCode);
        sb.append(", tranRemark=").append(tranRemark);
        sb.append(", remark=").append(remark);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}