package com.unionpay.dao.model;

import java.io.Serializable;
import java.util.Date;

public class UpIntegralAccount implements Serializable
{
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.integral_account_no
	 *
	 * @mbg.generated
	 */
	private String integralAccountNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.account_type
	 *
	 * @mbg.generated
	 */
	private String accountType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.org_code
	 *
	 * @mbg.generated
	 */
	private String orgCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.merch_id
	 *
	 * @mbg.generated
	 */
	private String merchId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.active_no_integral
	 *
	 * @mbg.generated
	 */
	private Long activeNoIntegral;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.available_balance
	 *
	 * @mbg.generated
	 */
	private Long availableBalance;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.blocked_balance
	 *
	 * @mbg.generated
	 */
	private Long blockedBalance;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.account_status
	 *
	 * @mbg.generated
	 */
	private String accountStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.temper
	 *
	 * @mbg.generated
	 */
	private String temper;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.account_change_time
	 *
	 * @mbg.generated
	 */
	private Date accountChangeTime;

	/**
	 * 账户变动日期
	 */
	private String changeDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column up_integral_account.created_time
	 *
	 * @mbg.generated
	 */
	private Date createdTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table up_integral_account
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.integral_account_no
	 *
	 * @return the value of up_integral_account.integral_account_no
	 *
	 * @mbg.generated
	 */
	public String getIntegralAccountNo()
	{
		return integralAccountNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.integral_account_no
	 *
	 * @param integralAccountNo
	 *            the value for up_integral_account.integral_account_no
	 *
	 * @mbg.generated
	 */
	public void setIntegralAccountNo(String integralAccountNo)
	{
		this.integralAccountNo = integralAccountNo == null ? null : integralAccountNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.account_type
	 *
	 * @return the value of up_integral_account.account_type
	 *
	 * @mbg.generated
	 */
	public String getAccountType()
	{
		return accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.account_type
	 *
	 * @param accountType
	 *            the value for up_integral_account.account_type
	 *
	 * @mbg.generated
	 */
	public void setAccountType(String accountType)
	{
		this.accountType = accountType == null ? null : accountType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.org_code
	 *
	 * @return the value of up_integral_account.org_code
	 *
	 * @mbg.generated
	 */
	public String getOrgCode()
	{
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.org_code
	 *
	 * @param orgCode
	 *            the value for up_integral_account.org_code
	 *
	 * @mbg.generated
	 */
	public void setOrgCode(String orgCode)
	{
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.merch_id
	 *
	 * @return the value of up_integral_account.merch_id
	 *
	 * @mbg.generated
	 */
	public String getMerchId()
	{
		return merchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.merch_id
	 *
	 * @param merchId
	 *            the value for up_integral_account.merch_id
	 *
	 * @mbg.generated
	 */
	public void setMerchId(String merchId)
	{
		this.merchId = merchId == null ? null : merchId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.active_no_integral
	 *
	 * @return the value of up_integral_account.active_no_integral
	 *
	 * @mbg.generated
	 */
	public Long getActiveNoIntegral()
	{
		return activeNoIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.active_no_integral
	 *
	 * @param activeNoIntegral
	 *            the value for up_integral_account.active_no_integral
	 *
	 * @mbg.generated
	 */
	public void setActiveNoIntegral(Long activeNoIntegral)
	{
		this.activeNoIntegral = activeNoIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.available_balance
	 *
	 * @return the value of up_integral_account.available_balance
	 *
	 * @mbg.generated
	 */
	public Long getAvailableBalance()
	{
		return availableBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.available_balance
	 *
	 * @param availableBalance
	 *            the value for up_integral_account.available_balance
	 *
	 * @mbg.generated
	 */
	public void setAvailableBalance(Long availableBalance)
	{
		this.availableBalance = availableBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.blocked_balance
	 *
	 * @return the value of up_integral_account.blocked_balance
	 *
	 * @mbg.generated
	 */
	public Long getBlockedBalance()
	{
		return blockedBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.blocked_balance
	 *
	 * @param blockedBalance
	 *            the value for up_integral_account.blocked_balance
	 *
	 * @mbg.generated
	 */
	public void setBlockedBalance(Long blockedBalance)
	{
		this.blockedBalance = blockedBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.account_status
	 *
	 * @return the value of up_integral_account.account_status
	 *
	 * @mbg.generated
	 */
	public String getAccountStatus()
	{
		return accountStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.account_status
	 *
	 * @param accountStatus
	 *            the value for up_integral_account.account_status
	 *
	 * @mbg.generated
	 */
	public void setAccountStatus(String accountStatus)
	{
		this.accountStatus = accountStatus == null ? null : accountStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.temper
	 *
	 * @return the value of up_integral_account.temper
	 *
	 * @mbg.generated
	 */
	public String getTemper()
	{
		return temper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.temper
	 *
	 * @param temper
	 *            the value for up_integral_account.temper
	 *
	 * @mbg.generated
	 */
	public void setTemper(String temper)
	{
		this.temper = temper == null ? null : temper.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.account_change_time
	 *
	 * @return the value of up_integral_account.account_change_time
	 *
	 * @mbg.generated
	 */
	public Date getAccountChangeTime()
	{
		return accountChangeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.account_change_time
	 *
	 * @param accountChangeTime
	 *            the value for up_integral_account.account_change_time
	 *
	 * @mbg.generated
	 */
	public void setAccountChangeTime(Date accountChangeTime)
	{
		this.accountChangeTime = accountChangeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column up_integral_account.created_time
	 *
	 * @return the value of up_integral_account.created_time
	 *
	 * @mbg.generated
	 */
	public Date getCreatedTime()
	{
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column up_integral_account.created_time
	 *
	 * @param createdTime
	 *            the value for up_integral_account.created_time
	 *
	 * @mbg.generated
	 */
	public void setCreatedTime(Date createdTime)
	{
		this.createdTime = createdTime;
	}

	public String getChangeDate()
	{
		return changeDate;
	}

	public void setChangeDate(String changeDate)
	{
		this.changeDate = changeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table up_integral_account
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that)
	{
		if (this == that)
		{
			return true;
		}
		if (that == null)
		{
			return false;
		}
		if (getClass() != that.getClass())
		{
			return false;
		}
		UpIntegralAccount other = (UpIntegralAccount) that;
		return (this.getIntegralAccountNo() == null ? other.getIntegralAccountNo() == null
				: this.getIntegralAccountNo().equals(other.getIntegralAccountNo()))
				&& (this.getAccountType() == null ? other.getAccountType() == null
						: this.getAccountType().equals(other.getAccountType()))
				&& (this.getOrgCode() == null ? other.getOrgCode() == null
						: this.getOrgCode().equals(other.getOrgCode()))
				&& (this.getMerchId() == null ? other.getMerchId() == null
						: this.getMerchId().equals(other.getMerchId()))
				&& (this.getActiveNoIntegral() == null ? other.getActiveNoIntegral() == null
						: this.getActiveNoIntegral().equals(other.getActiveNoIntegral()))
				&& (this.getAvailableBalance() == null ? other.getAvailableBalance() == null
						: this.getAvailableBalance().equals(other.getAvailableBalance()))
				&& (this.getBlockedBalance() == null ? other.getBlockedBalance() == null
						: this.getBlockedBalance().equals(other.getBlockedBalance()))
				&& (this.getAccountStatus() == null ? other.getAccountStatus() == null
						: this.getAccountStatus().equals(other.getAccountStatus()))
				&& (this.getTemper() == null ? other.getTemper() == null : this.getTemper().equals(other.getTemper()))
				&& (this.getAccountChangeTime() == null ? other.getAccountChangeTime() == null
						: this.getAccountChangeTime().equals(other.getAccountChangeTime()))
				&& (this.getCreatedTime() == null ? other.getCreatedTime() == null
						: this.getCreatedTime().equals(other.getCreatedTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table up_integral_account
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getIntegralAccountNo() == null) ? 0 : getIntegralAccountNo().hashCode());
		result = prime * result + ((getAccountType() == null) ? 0 : getAccountType().hashCode());
		result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
		result = prime * result + ((getMerchId() == null) ? 0 : getMerchId().hashCode());
		result = prime * result + ((getActiveNoIntegral() == null) ? 0 : getActiveNoIntegral().hashCode());
		result = prime * result + ((getAvailableBalance() == null) ? 0 : getAvailableBalance().hashCode());
		result = prime * result + ((getBlockedBalance() == null) ? 0 : getBlockedBalance().hashCode());
		result = prime * result + ((getAccountStatus() == null) ? 0 : getAccountStatus().hashCode());
		result = prime * result + ((getTemper() == null) ? 0 : getTemper().hashCode());
		result = prime * result + ((getAccountChangeTime() == null) ? 0 : getAccountChangeTime().hashCode());
		result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table up_integral_account
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", integralAccountNo=").append(integralAccountNo);
		sb.append(", accountType=").append(accountType);
		sb.append(", orgCode=").append(orgCode);
		sb.append(", merchId=").append(merchId);
		sb.append(", activeNoIntegral=").append(activeNoIntegral);
		sb.append(", availableBalance=").append(availableBalance);
		sb.append(", blockedBalance=").append(blockedBalance);
		sb.append(", accountStatus=").append(accountStatus);
		sb.append(", temper=").append(temper);
		sb.append(", accountChangeTime=").append(accountChangeTime);
		sb.append(", createdTime=").append(createdTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}